baseurl: /
languageCode: en-us
title: Raghul - Fundamentals of Business Analytics
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/raghulmohankumar
    - name: Twitter
      url: https://twitter.com/eee_rahulrahul
    - name: LinkedIn
      url: https://www.linkedin.com/in/raghul-mohankumar-51811763/  
    - name: Facebook
      url: https://www.facebook.com/rahul.mohan.54/  
    - name: Instagram
      url: https://www.instagram.com/rahulmohankumar/   
      
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes

