baseurl: /
languageCode: en-us
title: Raghul - Fundamentals of Business Analytics
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/raghulmohankumar
    - name: Twitter
      url: https://twitter.com/eee_rahulrahul
    - name: LinkedIn
      url: https://www.linkedin.com/in/raghul-mohankumar-51811763/  
    - name: Facebook
      url: https://www.facebook.com/rahul.mohan.54/  
    - name: Instagram
      url: https://www.instagram.com/rahulmohankumar/   
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.jpg
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes

Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Example name"
  profession: "Profession"
  github: "https://github.com"
  linkedin: "https://linkedin.com"
  twitter: "https://twitter.com/"
  instagram: "https://instagram.com/"
  facebook: "https://facebook.com"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Profile, a passionate web developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
  descripe_l2_person: "This is a example template for about section. You can find my works [here](#projects)"
  skills:
    - name: CSS
      percentage: 90
    - name: Django
      percentage: 85
    - name: Hugo
      percentage: 80
    - name: React JS
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Google"
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
