---
title: Data Wrangling using Tidyverse
author: ''
date: '2021-05-25'
slug: data-wrangling-using-tidyverse
categories:
  - Tidyverse
tags: []
---

## Import the Hotels.csv file

```{r warning=FALSE}
library(tidyverse)
hotels <- read_csv("hotels.csv")
head(hotels)
names(hotels)
glimpse(hotels)
```

## Select a variable 
```{r}
select(hotels,hotel,lead_time)
hotels %>%
  select(hotel,lead_time) %>%
  arrange(desc(lead_time))
```

## select a range of variables

```{r}
hotels %>%
  select(hotel:arrival_date_month)

hotels %>%
  select(starts_with("arrival"))
```

## Select a range of rows / cases

```{r}
hotels %>%
  # We will select 1st, 5th, 8th and 10 rows
  slice(c(1,5,8,10))

hotels %>%
  filter(hotel == "City Hotel")

hotels %>%
filter(
adults == 0,
children >= 1
) %>%
select(adults, babies, children)
hotels %>%
filter(
adults == 0,
children >= 1 & babies >= 1 # & means and
) %>%
select(hotel, adults, babies, children)
```

## Select and summarize 

```{r}
hotels %>%
  count(hotel,market_segment)
```

## Mutation
```{r}
little_ones <- hotels
little_ones %<>%
  mutate(little_ones = children + babies) %>%
  select(children,babies,little_ones) %>%
  arrange(desc(little_ones))
```

## Summary

```{r}

summary <- hotels %>%
  group_by(hotel) %>%
  summarize(mean_adr = mean(adr))
summary
```




