---
title: Modelling
author: Raghul, Nouran and Mona
date: '2021-07-22'
slug: modelling
categories:
  - ggplot2
  - models
  - Tidyverse
tags: []
---


<style>
body {
text-align: justify}
</style>

## Load Packages
```{r warning=FALSE,echo=FALSE,message=FALSE}
library(dplyr)
library(car)
library(ggplot2)
library(pROC)
library(caret)
library(caTools)
library(e1071)
library(kernlab)
```

## Import Datasets : Bank data
```{r warning=FALSE,echo=FALSE,message=FALSE}
credit=read.csv("credit_bureau.csv",sep = ",",stringsAsFactors = TRUE) 
demogs=read.csv("demogs.csv", sep = ",",stringsAsFactors = TRUE) 

col_order <- c("Application.ID","Education","Profession","Type.of.residence","Marital.Status..at.the.time.of.application.","Gender","Age","No.of.dependents","Income","No.of.months.in.current.residence","No.of.months.in.current.company","Performance.Tag")
demogs <- demogs[, col_order]
demogs_data = demogs[7:12]
demogs_data$Performance.Tag = factor(demogs_data$Performance.Tag)
```


## Seperating and feature scaling dataset

```{r warning=FALSE,echo=FALSE,message=FALSE}
set.seed(123)
split = sample.split(demogs_data$Performance.Tag, SplitRatio = 0.75)
training_set = subset(demogs_data, split == TRUE)
training_set[-3] <- as.numeric(unlist(training_set[-3]))
training_set[-3] = scale(training_set[-3])

test_set = subset(demogs_data, split == FALSE)
test_set[-3] <- as.numeric(unlist(training_set[-3]))
test_set[-3] = scale(test_set[-3])

```

## Fitting SVM to the training set

```{r echo=FALSE, message=FALSE, warning=FALSE}
#classifier = svm(formula = Performance.Tag ~ ., data = training_set,type = 'C-classification',kernel = 'linear')
trctrl <- trainControl(method = "repeatedcv", number = 2, repeats = 3)
svm_Linear <- train(Performance.Tag ~., data = training_set, method = "svmLinear",na.action = na.pass,
trControl=trctrl,
preProcess = c("center", "scale"),
tuneLength = 10)
#print(classifier)
svm_Linear
```