---
title: DataIO
author: ''
date: '2021-06-01'
slug: dataio
categories:
  - Tidyverse
tags: []
---

```{r}
library(tidyverse)
nobel <- read_csv(file = "nobel.csv")
```

# Write a CSV file

```{r}
df <- tribble(
  ~x, ~y,
  1,  "a",
  2,  "b",
  3,  "c"
)


write_csv(df, file = "df, df.csv")
```

#Dealing with the bad names

```{r}
edibnb_badnames <- read_csv("edibnb-badnames.csv")
names(edibnb_badnames)

edibnb_col_names <- read_csv("edibnb-badnames.csv",
                             col_names = c("id", "price", 
                                           "neighbourhood", "accommodates",
                                           "bathroom", "bedroom", 
                                           "bed", "review_scores_rating", 
                                           "n_reviews", "url"))

names(edibnb_col_names)

```

## Importing Data with snake case Variables

```{r}

edibnb_clean_names <- read_csv("edibnb-badnames.csv") %>%
  janitor::clean_names()
names(edibnb_clean_names)

```

## Read df-na.csv

```{r}

read_csv("df-na.csv", na = c("", "NA", ".", "9999", "Not applicable"))
```

## Reading an XLSX file

```{r}
library(readxl)
fav_food <- read_excel("favourite-food.xlsx",
                       na = c("N/A", "99999")) %>%
  janitor::clean_names()
fav_food

fav_food <- fav_food %>%
  mutate(
    age = if_else(age == "five", "5", age),
    age = as.numeric(age)
    )
glimpse(fav_food)

```

## ETS of SES Variable

```{r}

fav_food %>%
  count(ses)

fav_food <- fav_food %>%
  mutate(ses = fct_relevel(ses, "Low", "Middle", "High"))

fav_food %>%
  count(ses)

```

