---
title: Logistic Regression Model
author: Raghul Mohankumar
date: '2021-07-16'
slug: logistic-regression-model
categories:
  - ggplot2
  - caret
  - models
  - Tidyverse
tags: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<style>
body {
text-align: justify}
</style>
<div id="problem-statement" class="section level2">
<h2>Problem Statement:</h2>
<p>The data is related with direct marketing campaigns of a Portuguese banking institution, which is rolling out term deposit for its customers. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be (or not) subscribed. The classification goal is to predict if the client will subscribe a term deposit (variable y).</p>
</div>
<div id="data" class="section level2">
<h2>Data:</h2>
<p>There are two datasets:</p>
<pre><code>  1) bank-full.csv with all examples, ordered by date (from May 2008 to November 2010).
  
  2) bank.csv with 10% of the examples (4521), randomly selected from bank-full.csv.
  </code></pre>
<p>The smallest dataset is provided to test more computationally demanding machine learning algorithms (e.g. SVM).</p>
<p>Number of Instances: 45211 for bank-full.csv (4521 for bank.csv)
Number of Attributes: 16 + output attribute</p>
</div>
<div id="data-dictionary" class="section level2">
<h2>Data dictionary:</h2>
<div id="variables-definition-type-and-their-categories" class="section level3">
<h3>Variables : Definition: Type and their categories</h3>
<p>Each row represents characteristic of a single customer . Many categorical data has been coded to mask the data.</p>
<p>1 - age (numeric)</p>
<p>2 - job : type of job (categorical: “admin.”, “unknown”, “unemployed”, “management”, “housemaid”, “entrepreneur”, “student”, “blue-collar”, “self-employed”, “retired”,“technician”, “services”)</p>
<p>3 - marital : marital status (categorical: “married”, “divorced”, “single”; note: “divorced” means divorced or widowed)</p>
<p>4 - education (categorical: “unknown”, “secondary”, “primary”, “tertiary”)</p>
<p>5 - default: has credit in default? (binary: “yes”, “no”)</p>
<p>6 - balance: average yearly balance, in euros (numeric)</p>
<p>7 - housing: has housing loan? (binary: “yes”,“no”)</p>
<p>8 - loan: has personal loan? (binary: “yes”,“no”)</p>
<p>Related with the last contact of the current campaign:</p>
<p>9 - contact: contact communication type (categorical: “unknown”, “telephone”, “cellular”)</p>
<p>10 - day: last contact day of the month (numeric))</p>
<p>Direct Marketing Campaign: Details and Phase I Tasks</p>
<p>11 - month: last contact month of year (categorical: “jan”, “feb”, “mar”, . . . , “nov”, “dec”)</p>
<p>12 - duration: last contact duration, in seconds (numeric)</p>
<p>other attributes: 13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)</p>
<p>14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)</p>
<p>15 - previous: number of contacts performed before this campaign and for this client (numeric)</p>
<p>16 - poutcome: outcome of the previous marketing campaign (categorical: “unknown”, “other”, “failure”, “success”)</p>
<p>Output variable (desired target):</p>
<p>17 - y - has the client subscribed a term deposit? (binary: “yes”,“no”)</p>
</div>
</div>
<div id="methodology" class="section level2">
<h2>Methodology:</h2>
<p>We will build a Logistic regression model to predict the response variable “y” (whether the client subscribed to a term deposit or No.)</p>
<p>Step 1: Imputing NA values in the datasets.</p>
<p>Step 2:Data Preparation: Grouping similar category variables and making dummies.</p>
<p>Step 3: Model Building( LOGISTIC REGRESSION )</p>
<p>Step 4. Finding Cutoff value and Perfomance measurements of the model.(Sensitivity, Specificity, Accuracy)</p>
<p>Step 5.Predict the final output on test dataset.(whether the client subscribe or no to term deposit)</p>
<p>Step 6:Creating confusion matrix and finding how good the model is.</p>
</div>
<div id="load-packages" class="section level2">
<h2>Load Packages</h2>
</div>
<div id="import-datasets-bank-data" class="section level2">
<h2>Import Datasets : Bank data</h2>
</div>
<div id="step-1-adding-na-values-in-the-datasets" class="section level2">
<h2>Step 1: Adding NA values in the datasets</h2>
<pre><code>##       age       job   marital education   default   balance   housing      loan 
##         0         0         0         0         0         0         0         0 
##   contact       day     month  duration  campaign     pdays  previous  poutcome 
##         0         0         0         0         0         0         0         0 
##         y 
##         0</code></pre>
<pre><code>##       age       job   marital education   default   balance   housing      loan 
##         0         0         0         0         0         0         0         0 
##   contact       day     month  duration  campaign     pdays  previous  poutcome 
##         0         0         0         0         0         0         0         0 
##         y 
##         0</code></pre>
<p>There are no NA values in train and test datasets.</p>
</div>
<div id="step-2data-preparation" class="section level2">
<h2>Step 2:Data Preparation</h2>
<p>Combining both train and test datasets prior to data preparation.</p>
<pre><code>##       age       job   marital education   default   balance   housing      loan 
##         0         0         0         0         0         0         0         0 
##   contact       day     month  duration  campaign     pdays  previous  poutcome 
##         0         0         0         0         0         0         0         0 
##         y      data 
##      4521         0</code></pre>
<pre><code>## Rows: 49,732
## Columns: 17
## $ age       &lt;int&gt; 58, 44, 33, 47, 33, 35, 28, 42, 58, 43, 41, 29, 53, 58, 57, ~
## $ job       &lt;chr&gt; &quot;management&quot;, &quot;technician&quot;, &quot;entrepreneur&quot;, &quot;blue-collar&quot;, &quot;~
## $ marital   &lt;chr&gt; &quot;married&quot;, &quot;single&quot;, &quot;married&quot;, &quot;married&quot;, &quot;single&quot;, &quot;marrie~
## $ education &lt;chr&gt; &quot;tertiary&quot;, &quot;secondary&quot;, &quot;secondary&quot;, &quot;unknown&quot;, &quot;unknown&quot;, ~
## $ default   &lt;chr&gt; &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;yes&quot;, &quot;no&quot;, &quot;no&quot;,~
## $ housing   &lt;chr&gt; &quot;yes&quot;, &quot;yes&quot;, &quot;yes&quot;, &quot;yes&quot;, &quot;no&quot;, &quot;yes&quot;, &quot;yes&quot;, &quot;yes&quot;, &quot;yes&quot;~
## $ loan      &lt;chr&gt; &quot;no&quot;, &quot;no&quot;, &quot;yes&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;yes&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;~
## $ contact   &lt;chr&gt; &quot;unknown&quot;, &quot;unknown&quot;, &quot;unknown&quot;, &quot;unknown&quot;, &quot;unknown&quot;, &quot;unkn~
## $ day       &lt;int&gt; 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ~
## $ month     &lt;chr&gt; &quot;may&quot;, &quot;may&quot;, &quot;may&quot;, &quot;may&quot;, &quot;may&quot;, &quot;may&quot;, &quot;may&quot;, &quot;may&quot;, &quot;may~
## $ duration  &lt;int&gt; 261, 151, 76, 92, 198, 139, 217, 380, 50, 55, 222, 137, 517,~
## $ campaign  &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ~
## $ pdays     &lt;int&gt; -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ~
## $ previous  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
## $ poutcome  &lt;chr&gt; &quot;unknown&quot;, &quot;unknown&quot;, &quot;unknown&quot;, &quot;unknown&quot;, &quot;unknown&quot;, &quot;unkn~
## $ y         &lt;chr&gt; &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, &quot;no&quot;, ~
## $ data      &lt;chr&gt; &quot;train&quot;, &quot;train&quot;, &quot;train&quot;, &quot;train&quot;, &quot;train&quot;, &quot;train&quot;, &quot;train~</code></pre>
</div>
<div id="creating-dummy-variables-by-combining-similar-categories" class="section level2">
<h2>Creating dummy variables by combining similar categories</h2>
<div id="dummy-for-job" class="section level3">
<h3>Dummy for Job</h3>
<pre><code>## 
##       unknown       student     housemaid    unemployed  entrepreneur 
##           326          1022          1352          1431          1655 
## self-employed       retired      services        admin.    technician 
##          1762          2494          4571          5649          8365 
##    management   blue-collar 
##         10427         10678</code></pre>
<pre><code>##       student       retired    unemployed    management        admin. 
##          71.3          77.2          84.5          86.2          87.8 
## self-employed       unknown    technician      services     housemaid 
##          88.2          88.2          88.9          91.1          91.2 
##  entrepreneur   blue-collar 
##          91.7          92.7</code></pre>
</div>
<div id="dummy-for-marital" class="section level3">
<h3>Dummy for marital</h3>
<pre><code>## 
## divorced   single  married 
##     5735    13986    30011</code></pre>
</div>
<div id="dummy-for-education" class="section level3">
<h3>Dummy for education</h3>
<pre><code>## 
##   unknown   primary  tertiary secondary 
##      2044      7529     14651     25508</code></pre>
</div>
<div id="dummy-for-default" class="section level3">
<h3>Dummy for default</h3>
<pre><code>## 
##    no   yes 
## 48841   891</code></pre>
</div>
<div id="dummy-for-housing" class="section level3">
<h3>Dummy for housing</h3>
<pre><code>## 
##    no   yes 
## 22043 27689</code></pre>
</div>
<div id="dummy-for-loan" class="section level3">
<h3>Dummy for loan</h3>
<pre><code>## 
##    no   yes 
## 41797  7935</code></pre>
</div>
<div id="dummy-for-contact" class="section level3">
<h3>Dummy for contact</h3>
<pre><code>## 
## telephone   unknown  cellular 
##      3207     14344     32181</code></pre>
</div>
<div id="dummy-for-month" class="section level3">
<h3>Dummy for month</h3>
<pre><code>##  mar  dec  sep  oct  apr  feb  aug  jun  nov  jan  jul  may 
## 48.0 53.3 53.5 56.2 80.3 83.4 89.0 89.8 89.8 89.9 90.9 93.3</code></pre>
</div>
<div id="dummy-for-outcome" class="section level3">
<h3>Dummy for outcome</h3>
<pre><code>## 
## success   other failure unknown 
##    1640    2037    5391   40664</code></pre>
</div>
<div id="after-data-preparation" class="section level3">
<h3>After Data Preparation</h3>
<pre><code>## 
##    no   yes 
## 39922  5289</code></pre>
<pre><code>## 
##    no   yes 
## 39922  5289</code></pre>
<pre><code>## 
##     0     1 
## 39922  5289</code></pre>
<pre><code>## Rows: 49,732
## Columns: 33
## $ age         &lt;int&gt; 58, 44, 33, 47, 33, 35, 28, 42, 58, 43, 41, 29, 53, 58, 57~
## $ default     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ housing     &lt;dbl&gt; 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~
## $ loan        &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ day         &lt;int&gt; 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5~
## $ duration    &lt;int&gt; 261, 151, 76, 92, 198, 139, 217, 380, 50, 55, 222, 137, 51~
## $ campaign    &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~
## $ pdays       &lt;int&gt; -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1~
## $ previous    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ y           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ data        &lt;chr&gt; &quot;train&quot;, &quot;train&quot;, &quot;train&quot;, &quot;train&quot;, &quot;train&quot;, &quot;train&quot;, &quot;tra~
## $ job_1       &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0~
## $ job_2       &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1~
## $ job_3       &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ job_4       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ job_5       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0~
## $ job_6       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ divorced    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ single      &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0~
## $ edu_primary &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0~
## $ edu_sec     &lt;dbl&gt; 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1~
## $ edu_tert    &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ co_cellular &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ co_tel      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_1     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_2     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_3     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_4     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_5     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_6     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ poc_success &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ poc_failure &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ poc_other   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~</code></pre>
</div>
<div id="after-separating-test-and-train" class="section level3">
<h3>After Separating test and train</h3>
<pre><code>## Rows: 45,211
## Columns: 32
## $ age         &lt;int&gt; 58, 44, 33, 47, 33, 35, 28, 42, 58, 43, 41, 29, 53, 58, 57~
## $ default     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ housing     &lt;dbl&gt; 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~
## $ loan        &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ day         &lt;int&gt; 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5~
## $ duration    &lt;int&gt; 261, 151, 76, 92, 198, 139, 217, 380, 50, 55, 222, 137, 51~
## $ campaign    &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~
## $ pdays       &lt;int&gt; -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1~
## $ previous    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ y           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ job_1       &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0~
## $ job_2       &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1~
## $ job_3       &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ job_4       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ job_5       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0~
## $ job_6       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ divorced    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ single      &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0~
## $ edu_primary &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0~
## $ edu_sec     &lt;dbl&gt; 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1~
## $ edu_tert    &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ co_cellular &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ co_tel      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_1     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_2     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_3     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_4     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_5     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_6     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ poc_success &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ poc_failure &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ poc_other   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~</code></pre>
<pre><code>## Rows: 4,521
## Columns: 31
## $ age         &lt;int&gt; 30, 33, 35, 30, 59, 35, 36, 39, 41, 43, 39, 43, 36, 20, 31~
## $ default     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ housing     &lt;dbl&gt; 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0~
## $ loan        &lt;dbl&gt; 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0~
## $ day         &lt;int&gt; 19, 11, 16, 3, 5, 23, 14, 6, 14, 17, 20, 17, 13, 30, 29, 2~
## $ duration    &lt;int&gt; 79, 220, 185, 199, 226, 141, 341, 151, 57, 313, 273, 113, ~
## $ campaign    &lt;int&gt; 1, 1, 1, 4, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 5, 1, 1, 1~
## $ pdays       &lt;int&gt; -1, 339, 330, -1, -1, 176, 330, -1, -1, 147, -1, -1, -1, -~
## $ previous    &lt;int&gt; 0, 4, 1, 0, 0, 3, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1~
## $ job_1       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0~
## $ job_2       &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1~
## $ job_3       &lt;dbl&gt; 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0~
## $ job_4       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0~
## $ job_5       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ job_6       &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ divorced    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ single      &lt;dbl&gt; 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0~
## $ edu_primary &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0~
## $ edu_sec     &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1~
## $ edu_tert    &lt;dbl&gt; 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0~
## $ co_cellular &lt;dbl&gt; 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1~
## $ co_tel      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_1     &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1~
## $ month_2     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_3     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_4     &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ month_5     &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0~
## $ month_6     &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ poc_success &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ poc_failure &lt;dbl&gt; 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0~
## $ poc_other   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1~</code></pre>
</div>
</div>
<div id="step-3-model-building" class="section level2">
<h2>Step 3: Model Building</h2>
<p>We will use train for logistic regression model building and use train_25 to test the performance of the model thus built.
Lets build logistic regression model on train dataset.</p>
<pre><code>## 
## Call:
## lm(formula = y ~ ., data = train)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.25983 -0.10950 -0.03964  0.02150  1.04915 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -4.833e-02  1.072e-02  -4.509 6.52e-06 ***
## age          1.865e-04  1.554e-04   1.200  0.23004    
## default     -4.667e-03  9.574e-03  -0.487  0.62596    
## housing     -5.068e-02  2.990e-03 -16.950  &lt; 2e-16 ***
## loan        -2.705e-02  3.508e-03  -7.711 1.27e-14 ***
## day         -1.737e-05  1.628e-04  -0.107  0.91503    
## duration     4.701e-04  4.957e-06  94.845  &lt; 2e-16 ***
## campaign    -1.017e-03  4.226e-04  -2.406  0.01614 *  
## pdays       -3.396e-05  2.710e-05  -1.253  0.21016    
## previous     1.075e-03  6.541e-04   1.643  0.10043    
## job_1       -3.609e-03  3.771e-03  -0.957  0.33854    
## job_2       -6.996e-03  3.980e-03  -1.758  0.07879 .  
## job_3        4.987e-04  4.576e-03   0.109  0.91321    
## job_4        8.261e-02  9.568e-03   8.634  &lt; 2e-16 ***
## job_5        4.098e-02  6.902e-03   5.937 2.92e-09 ***
## job_6        4.068e-03  7.888e-03   0.516  0.60609    
## divorced     1.338e-02  4.106e-03   3.260  0.00112 ** 
## single       2.289e-02  3.251e-03   7.041 1.94e-12 ***
## edu_primary -1.458e-02  7.167e-03  -2.035  0.04189 *  
## edu_sec     -2.983e-03  6.599e-03  -0.452  0.65123    
## edu_tert     1.353e-02  7.040e-03   1.922  0.05459 .  
## co_cellular  4.524e-02  3.375e-03  13.406  &lt; 2e-16 ***
## co_tel       3.288e-02  5.883e-03   5.589 2.30e-08 ***
## month_1     -5.984e-03  3.502e-03  -1.709  0.08747 .  
## month_2      2.064e-01  1.029e-02  20.053  &lt; 2e-16 ***
## month_3      3.337e-01  1.285e-02  25.975  &lt; 2e-16 ***
## month_4      2.133e-01  1.057e-02  20.173  &lt; 2e-16 ***
## month_5      5.870e-02  5.805e-03  10.112  &lt; 2e-16 ***
## month_6      3.085e-02  6.389e-03   4.828 1.39e-06 ***
## poc_success  4.334e-01  8.843e-03  49.010  &lt; 2e-16 ***
## poc_failure  1.575e-02  8.039e-03   1.959  0.05015 .  
## poc_other    3.920e-02  9.422e-03   4.161 3.18e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2695 on 45179 degrees of freedom
## Multiple R-squared:  0.2976, Adjusted R-squared:  0.2971 
## F-statistic: 617.5 on 31 and 45179 DF,  p-value: &lt; 2.2e-16</code></pre>
<div id="fine-tuning-for-multi-collinearity" class="section level3">
<h3>Fine tuning for multi-collinearity</h3>
<pre><code>##     edu_sec    edu_tert       pdays edu_primary poc_failure 
##    6.773766    6.408443    4.584444    4.112661    3.888840</code></pre>
<pre><code>##       pdays poc_failure   poc_other       job_3     month_1 
##    4.584412    3.888836    2.158117    2.152767    1.902953</code></pre>
<pre><code>## 
## Call:
## glm(formula = y ~ ., family = &quot;binomial&quot;, data = fit_train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -5.6965  -0.3818  -0.2571  -0.1608   3.2832  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -4.180e+00  1.267e-01 -33.003  &lt; 2e-16 ***
## age          4.720e-04  2.157e-03   0.219  0.82679    
## default     -8.702e-02  1.620e-01  -0.537  0.59105    
## housing     -7.301e-01  4.280e-02 -17.057  &lt; 2e-16 ***
## loan        -4.831e-01  5.881e-02  -8.216  &lt; 2e-16 ***
## day         -2.603e-03  2.305e-03  -1.129  0.25875    
## duration     4.123e-03  6.357e-05  64.862  &lt; 2e-16 ***
## campaign    -8.587e-02  9.874e-03  -8.696  &lt; 2e-16 ***
## pdays        2.188e-05  3.033e-04   0.072  0.94250    
## previous     1.022e-02  6.572e-03   1.555  0.11996    
## job_1       -4.821e-02  5.506e-02  -0.876  0.38125    
## job_2       -1.294e-01  6.223e-02  -2.080  0.03753 *  
## job_3       -1.723e-03  6.329e-02  -0.027  0.97828    
## job_4        5.691e-01  1.016e-01   5.601 2.13e-08 ***
## job_5        4.471e-01  8.794e-02   5.084 3.70e-07 ***
## job_6       -1.333e-02  1.046e-01  -0.127  0.89859    
## divorced     1.916e-01  5.836e-02   3.284  0.00102 ** 
## single       2.988e-01  4.543e-02   6.578 4.76e-11 ***
## edu_primary -2.667e-01  6.083e-02  -4.385 1.16e-05 ***
## edu_tert     2.003e-01  4.884e-02   4.102 4.10e-05 ***
## co_cellular  1.023e+00  6.164e-02  16.603  &lt; 2e-16 ***
## co_tel       8.474e-01  9.260e-02   9.151  &lt; 2e-16 ***
## month_1     -5.869e-02  5.527e-02  -1.062  0.28828    
## month_2      1.342e+00  1.013e-01  13.244  &lt; 2e-16 ***
## month_3      2.154e+00  1.161e-01  18.551  &lt; 2e-16 ***
## month_4      1.477e+00  1.047e-01  14.113  &lt; 2e-16 ***
## month_5      6.243e-01  7.176e-02   8.700  &lt; 2e-16 ***
## month_6      3.211e-01  8.190e-02   3.920 8.86e-05 ***
## poc_success  2.427e+00  8.497e-02  28.559  &lt; 2e-16 ***
## poc_failure  1.227e-01  9.195e-02   1.334  0.18212    
## poc_other    3.433e-01  1.052e-01   3.264  0.00110 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 32631  on 45210  degrees of freedom
## Residual deviance: 21860  on 45180  degrees of freedom
## AIC: 21922
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<pre><code>## Start:  AIC=21921.61
## y ~ age + default + housing + loan + day + duration + campaign + 
##     pdays + previous + job_1 + job_2 + job_3 + job_4 + job_5 + 
##     job_6 + divorced + single + edu_primary + edu_tert + co_cellular + 
##     co_tel + month_1 + month_2 + month_3 + month_4 + month_5 + 
##     month_6 + poc_success + poc_failure + poc_other
## 
##               Df Deviance   AIC
## - job_3        1    21860 21920
## - pdays        1    21860 21920
## - job_6        1    21860 21920
## - age          1    21860 21920
## - default      1    21860 21920
## - job_1        1    21860 21920
## - month_1      1    21861 21921
## - day          1    21861 21921
## - poc_failure  1    21861 21921
## &lt;none&gt;              21860 21922
## - previous     1    21862 21922
## - job_2        1    21864 21924
## - poc_other    1    21870 21930
## - divorced     1    21870 21930
## - month_6      1    21875 21935
## - edu_tert     1    21876 21936
## - edu_primary  1    21879 21939
## - job_5        1    21885 21945
## - job_4        1    21890 21950
## - single       1    21903 21963
## - loan         1    21932 21992
## - month_5      1    21934 21994
## - co_tel       1    21941 22001
## - campaign     1    21949 22009
## - month_2      1    22029 22089
## - month_4      1    22049 22109
## - housing      1    22159 22219
## - co_cellular  1    22169 22229
## - month_3      1    22182 22242
## - poc_success  1    22656 22716
## - duration     1    27379 27439
## 
## Step:  AIC=21919.61
## y ~ age + default + housing + loan + day + duration + campaign + 
##     pdays + previous + job_1 + job_2 + job_4 + job_5 + job_6 + 
##     divorced + single + edu_primary + edu_tert + co_cellular + 
##     co_tel + month_1 + month_2 + month_3 + month_4 + month_5 + 
##     month_6 + poc_success + poc_failure + poc_other
## 
##               Df Deviance   AIC
## - pdays        1    21860 21918
## - job_6        1    21860 21918
## - age          1    21860 21918
## - default      1    21860 21918
## - job_1        1    21861 21919
## - month_1      1    21861 21919
## - day          1    21861 21919
## - poc_failure  1    21861 21919
## &lt;none&gt;              21860 21920
## - previous     1    21862 21920
## - job_2        1    21865 21923
## - poc_other    1    21870 21928
## - divorced     1    21870 21928
## - month_6      1    21875 21933
## - edu_primary  1    21880 21938
## - edu_tert     1    21884 21942
## - job_5        1    21887 21945
## - job_4        1    21892 21950
## - single       1    21903 21961
## - loan         1    21932 21990
## - month_5      1    21934 21992
## - co_tel       1    21941 21999
## - campaign     1    21949 22007
## - month_2      1    22030 22088
## - month_4      1    22049 22107
## - housing      1    22160 22218
## - co_cellular  1    22169 22227
## - month_3      1    22182 22240
## - poc_success  1    22656 22714
## - duration     1    27379 27437
## 
## Step:  AIC=21917.61
## y ~ age + default + housing + loan + day + duration + campaign + 
##     previous + job_1 + job_2 + job_4 + job_5 + job_6 + divorced + 
##     single + edu_primary + edu_tert + co_cellular + co_tel + 
##     month_1 + month_2 + month_3 + month_4 + month_5 + month_6 + 
##     poc_success + poc_failure + poc_other
## 
##               Df Deviance   AIC
## - job_6        1    21860 21916
## - age          1    21860 21916
## - default      1    21860 21916
## - job_1        1    21861 21917
## - month_1      1    21861 21917
## - day          1    21861 21917
## &lt;none&gt;              21860 21918
## - previous     1    21862 21918
## - poc_failure  1    21864 21920
## - job_2        1    21865 21921
## - divorced     1    21870 21926
## - month_6      1    21875 21931
## - poc_other    1    21876 21932
## - edu_primary  1    21880 21936
## - edu_tert     1    21884 21940
## - job_5        1    21887 21943
## - job_4        1    21892 21948
## - single       1    21903 21959
## - loan         1    21932 21988
## - month_5      1    21934 21990
## - co_tel       1    21941 21997
## - campaign     1    21949 22005
## - month_2      1    22030 22086
## - month_4      1    22049 22105
## - housing      1    22161 22217
## - co_cellular  1    22170 22226
## - month_3      1    22183 22239
## - poc_success  1    23058 23114
## - duration     1    27379 27435
## 
## Step:  AIC=21915.63
## y ~ age + default + housing + loan + day + duration + campaign + 
##     previous + job_1 + job_2 + job_4 + job_5 + divorced + single + 
##     edu_primary + edu_tert + co_cellular + co_tel + month_1 + 
##     month_2 + month_3 + month_4 + month_5 + month_6 + poc_success + 
##     poc_failure + poc_other
## 
##               Df Deviance   AIC
## - age          1    21860 21914
## - default      1    21860 21914
## - job_1        1    21861 21915
## - month_1      1    21861 21915
## - day          1    21861 21915
## &lt;none&gt;              21860 21916
## - previous     1    21862 21916
## - poc_failure  1    21864 21918
## - job_2        1    21865 21919
## - divorced     1    21870 21924
## - month_6      1    21875 21929
## - poc_other    1    21876 21930
## - edu_primary  1    21880 21934
## - edu_tert     1    21884 21938
## - job_5        1    21888 21942
## - job_4        1    21892 21946
## - single       1    21903 21957
## - loan         1    21933 21987
## - month_5      1    21934 21988
## - co_tel       1    21941 21995
## - campaign     1    21949 22003
## - month_2      1    22030 22084
## - month_4      1    22049 22103
## - housing      1    22162 22216
## - co_cellular  1    22170 22224
## - month_3      1    22183 22237
## - poc_success  1    23058 23112
## - duration     1    27382 27436
## 
## Step:  AIC=21913.68
## y ~ default + housing + loan + day + duration + campaign + previous + 
##     job_1 + job_2 + job_4 + job_5 + divorced + single + edu_primary + 
##     edu_tert + co_cellular + co_tel + month_1 + month_2 + month_3 + 
##     month_4 + month_5 + month_6 + poc_success + poc_failure + 
##     poc_other
## 
##               Df Deviance   AIC
## - default      1    21860 21912
## - job_1        1    21861 21913
## - month_1      1    21861 21913
## - day          1    21861 21913
## &lt;none&gt;              21860 21914
## - previous     1    21862 21914
## - poc_failure  1    21864 21916
## - job_2        1    21865 21917
## - divorced     1    21870 21922
## - month_6      1    21875 21927
## - poc_other    1    21876 21928
## - edu_primary  1    21880 21932
## - edu_tert     1    21884 21936
## - job_4        1    21893 21945
## - job_5        1    21898 21950
## - single       1    21909 21961
## - loan         1    21933 21985
## - month_5      1    21934 21986
## - co_tel       1    21942 21994
## - campaign     1    21949 22001
## - month_2      1    22030 22082
## - month_4      1    22050 22102
## - housing      1    22168 22220
## - co_cellular  1    22170 22222
## - month_3      1    22183 22235
## - poc_success  1    23060 23112
## - duration     1    27383 27435
## 
## Step:  AIC=21911.97
## y ~ housing + loan + day + duration + campaign + previous + job_1 + 
##     job_2 + job_4 + job_5 + divorced + single + edu_primary + 
##     edu_tert + co_cellular + co_tel + month_1 + month_2 + month_3 + 
##     month_4 + month_5 + month_6 + poc_success + poc_failure + 
##     poc_other
## 
##               Df Deviance   AIC
## - job_1        1    21861 21911
## - month_1      1    21861 21911
## - day          1    21861 21911
## &lt;none&gt;              21860 21912
## - previous     1    21863 21913
## - poc_failure  1    21865 21915
## - job_2        1    21865 21915
## - divorced     1    21871 21921
## - month_6      1    21875 21925
## - poc_other    1    21877 21927
## - edu_primary  1    21880 21930
## - edu_tert     1    21885 21935
## - job_4        1    21893 21943
## - job_5        1    21899 21949
## - single       1    21909 21959
## - month_5      1    21934 21984
## - loan         1    21934 21984
## - co_tel       1    21943 21993
## - campaign     1    21949 21999
## - month_2      1    22030 22080
## - month_4      1    22051 22101
## - housing      1    22168 22218
## - co_cellular  1    22170 22220
## - month_3      1    22184 22234
## - poc_success  1    23062 23112
## - duration     1    27384 27434
## 
## Step:  AIC=21910.96
## y ~ housing + loan + day + duration + campaign + previous + job_2 + 
##     job_4 + job_5 + divorced + single + edu_primary + edu_tert + 
##     co_cellular + co_tel + month_1 + month_2 + month_3 + month_4 + 
##     month_5 + month_6 + poc_success + poc_failure + poc_other
## 
##               Df Deviance   AIC
## - month_1      1    21862 21910
## - day          1    21862 21910
## &lt;none&gt;              21861 21911
## - previous     1    21864 21912
## - job_2        1    21865 21913
## - poc_failure  1    21866 21914
## - divorced     1    21872 21920
## - month_6      1    21876 21924
## - poc_other    1    21878 21926
## - edu_primary  1    21880 21928
## - edu_tert     1    21887 21935
## - job_4        1    21897 21945
## - job_5        1    21902 21950
## - single       1    21910 21958
## - month_5      1    21935 21983
## - loan         1    21935 21983
## - co_tel       1    21944 21992
## - campaign     1    21950 21998
## - month_2      1    22031 22079
## - month_4      1    22051 22099
## - housing      1    22169 22217
## - co_cellular  1    22171 22219
## - month_3      1    22185 22233
## - poc_success  1    23063 23111
## - duration     1    27385 27433
## 
## Step:  AIC=21910.22
## y ~ housing + loan + day + duration + campaign + previous + job_2 + 
##     job_4 + job_5 + divorced + single + edu_primary + edu_tert + 
##     co_cellular + co_tel + month_2 + month_3 + month_4 + month_5 + 
##     month_6 + poc_success + poc_failure + poc_other
## 
##               Df Deviance   AIC
## - day          1    21864 21910
## &lt;none&gt;              21862 21910
## - previous     1    21865 21911
## - job_2        1    21867 21913
## - poc_failure  1    21867 21913
## - divorced     1    21873 21919
## - poc_other    1    21880 21926
## - edu_primary  1    21881 21927
## - edu_tert     1    21888 21934
## - month_6      1    21888 21934
## - job_4        1    21898 21944
## - job_5        1    21904 21950
## - single       1    21913 21959
## - loan         1    21938 21984
## - co_tel       1    21944 21990
## - campaign     1    21953 21999
## - month_5      1    21975 22021
## - month_2      1    22078 22124
## - month_4      1    22099 22145
## - co_cellular  1    22191 22237
## - housing      1    22194 22240
## - month_3      1    22241 22287
## - poc_success  1    23071 23117
## - duration     1    27387 27433
## 
## Step:  AIC=21909.73
## y ~ housing + loan + duration + campaign + previous + job_2 + 
##     job_4 + job_5 + divorced + single + edu_primary + edu_tert + 
##     co_cellular + co_tel + month_2 + month_3 + month_4 + month_5 + 
##     month_6 + poc_success + poc_failure + poc_other
## 
##               Df Deviance   AIC
## &lt;none&gt;              21864 21910
## - previous     1    21866 21910
## - job_2        1    21868 21912
## - poc_failure  1    21869 21913
## - divorced     1    21875 21919
## - poc_other    1    21881 21925
## - edu_primary  1    21883 21927
## - edu_tert     1    21889 21933
## - month_6      1    21897 21941
## - job_4        1    21900 21944
## - job_5        1    21905 21949
## - single       1    21914 21958
## - loan         1    21939 21983
## - co_tel       1    21945 21989
## - campaign     1    21959 22003
## - month_5      1    21975 22019
## - month_2      1    22084 22128
## - month_4      1    22099 22143
## - co_cellular  1    22191 22235
## - housing      1    22194 22238
## - month_3      1    22245 22289
## - poc_success  1    23074 23118
## - duration     1    27393 27437</code></pre>
<pre><code>##  [1] &quot;(Intercept)&quot; &quot;housing&quot;     &quot;loan&quot;        &quot;duration&quot;    &quot;campaign&quot;   
##  [6] &quot;previous&quot;    &quot;job_2&quot;       &quot;job_4&quot;       &quot;job_5&quot;       &quot;divorced&quot;   
## [11] &quot;single&quot;      &quot;edu_primary&quot; &quot;edu_tert&quot;    &quot;co_cellular&quot; &quot;co_tel&quot;     
## [16] &quot;month_2&quot;     &quot;month_3&quot;     &quot;month_4&quot;     &quot;month_5&quot;     &quot;month_6&quot;    
## [21] &quot;poc_success&quot; &quot;poc_failure&quot; &quot;poc_other&quot;</code></pre>
</div>
<div id="building-final-logistic-model-on-significant-variables" class="section level3">
<h3>Building final logistic model on significant variables</h3>
<pre><code>## 
## Call:
## glm(formula = y ~ housing + loan + duration + campaign + previous + 
##     job_2 + job_4 + job_5 + divorced + single + edu_primary + 
##     edu_tert + co_cellular + co_tel + month_2 + month_3 + month_4 + 
##     month_5 + month_6 + poc_success + poc_failure + poc_other, 
##     family = &quot;binomial&quot;, data = fit_train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -5.7041  -0.3817  -0.2574  -0.1609   3.3052  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -4.249e+00  7.343e-02 -57.866  &lt; 2e-16 ***
## housing     -7.107e-01  3.955e-02 -17.969  &lt; 2e-16 ***
## loan        -4.886e-01  5.843e-02  -8.363  &lt; 2e-16 ***
## duration     4.125e-03  6.355e-05  64.908  &lt; 2e-16 ***
## campaign    -8.785e-02  9.798e-03  -8.966  &lt; 2e-16 ***
## previous     1.029e-02  6.576e-03   1.564 0.117705    
## job_2       -1.155e-01  5.602e-02  -2.062 0.039214 *  
## job_4        5.866e-01  9.544e-02   6.147 7.92e-10 ***
## job_5        4.703e-01  7.156e-02   6.572 4.97e-11 ***
## divorced     1.922e-01  5.807e-02   3.311 0.000931 ***
## single       2.953e-01  4.147e-02   7.121 1.07e-12 ***
## edu_primary -2.569e-01  5.984e-02  -4.293 1.76e-05 ***
## edu_tert     2.014e-01  3.992e-02   5.046 4.51e-07 ***
## co_cellular  1.000e+00  5.899e-02  16.960  &lt; 2e-16 ***
## co_tel       8.286e-01  9.048e-02   9.159  &lt; 2e-16 ***
## month_2      1.400e+00  9.154e-02  15.290  &lt; 2e-16 ***
## month_3      2.211e+00  1.075e-01  20.563  &lt; 2e-16 ***
## month_4      1.520e+00  9.493e-02  16.008  &lt; 2e-16 ***
## month_5      6.616e-01  6.082e-02  10.877  &lt; 2e-16 ***
## month_6      3.923e-01  6.683e-02   5.870 4.37e-09 ***
## poc_success  2.438e+00  6.863e-02  35.521  &lt; 2e-16 ***
## poc_failure  1.395e-01  5.924e-02   2.355 0.018509 *  
## poc_other    3.568e-01  8.249e-02   4.325 1.52e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 32631  on 45210  degrees of freedom
## Residual deviance: 21864  on 45188  degrees of freedom
## AIC: 21910
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<pre><code>##  [1] &quot;(Intercept)&quot; &quot;housing&quot;     &quot;loan&quot;        &quot;duration&quot;    &quot;campaign&quot;   
##  [6] &quot;previous&quot;    &quot;job_2&quot;       &quot;job_4&quot;       &quot;job_5&quot;       &quot;divorced&quot;   
## [11] &quot;single&quot;      &quot;edu_primary&quot; &quot;edu_tert&quot;    &quot;co_cellular&quot; &quot;co_tel&quot;     
## [16] &quot;month_2&quot;     &quot;month_3&quot;     &quot;month_4&quot;     &quot;month_5&quot;     &quot;month_6&quot;    
## [21] &quot;poc_success&quot; &quot;poc_failure&quot; &quot;poc_other&quot;</code></pre>
</div>
<div id="predict-scores-and-visualisation" class="section level3">
<h3>Predict Scores and visualisation</h3>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
</div>
<div id="step-4.-finding-cutoff-value-and-perfomance-measurements-of-the-model." class="section level2">
<h2>Step 4. Finding Cutoff value and Perfomance measurements of the model.</h2>
<pre><code>## [1] 0.1010101</code></pre>
<p>Therefore, 0.1010101 is the cutoff value by ks max method.</p>
</div>
<div id="step-5.predict-if-the-client-subscribe-or-no-to-term-deposit" class="section level2">
<h2>Step 5.Predict if the client subscribe or no to term deposit</h2>
<pre><code>## 
##   no  yes 
## 3308 1213</code></pre>
<p>Thus, 1213 customers out of 4521 subscribe to term deposit according to the model.</p>
</div>
<div id="step-6-creating-confusion-matrix-to-find-the-goodness-of-our-model" class="section level2">
<h2>Step 6: Creating confusion matrix to find the goodness of our model</h2>
<pre><code>## The Accuracy of the model is  0.8135893</code></pre>
<pre><code>## The Error of the model is  0.1864107 (according to ks method)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre><code>## Area under the curve: 0.9044</code></pre>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion:</h2>
<p>Ultimately, the target number of customers to be focused upon for term deposits by the bank are predicted successfully using logistic regression model with an accuracy of 81.35% using KS method. It predicts that 1213 customers out of 4521 subscribe to term deposit according to the model.The area under the ROC curve is 0.92/1, which shows that the model and predictions are very good.</p>
</div>
